In [85]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Because my Jupyter was showing only last line output, so need to add
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

Tit = pd.read_csv('C:/Users/admin/Python_Prac/Decision Tree/Titanic.csv')
Tit.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [86]:
Tit.columns
Tit.shape

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

(891, 12)

In [87]:
#target ratio
np.unique(Tit.Survived,return_counts=True)

(array([0, 1], dtype=int64), array([549, 342], dtype=int64))

In [88]:
549/(549+342)

0.6161616161616161

In [89]:
Tit.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [90]:
Tit1 =Tit.copy()
Tit1.shape
Tit1.describe()

(891, 12)

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [69]:
Tit1['Age']=Tit1['Age'].fillna(value=Tit1["Age"].mean())
Tit1.describe()
Tit1.isnull().sum()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   13.002015    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   29.699118    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [37]:
# incl cont - Age,Fare
#Cat - Pclass,Sex,Sibsp,Parch

In [91]:
# split the file into Independent and dependent variables
Setcolumns=list(['Age','Fare','Pclass','Sex','SibSp','Parch'])
Indepen=pd.DataFrame(Tit1,columns=Setcolumns)
Indepen.describe()

Age        Fare      Pclass       SibSp       Parch
count  714.000000  891.000000  891.000000  891.000000  891.000000
mean    29.699118   32.204208    2.308642    0.523008    0.381594
std     14.526497   49.693429    0.836071    1.102743    0.806057
min      0.420000    0.000000    1.000000    0.000000    0.000000
25%     20.125000    7.910400    2.000000    0.000000    0.000000
50%     28.000000   14.454200    3.000000    0.000000    0.000000
75%     38.000000   31.000000    3.000000    1.000000    0.000000
max     80.000000  512.329200    3.000000    8.000000    6.000000

In [93]:
Depen=pd.DataFrame(Tit1,columns=['Survived'])
Depen.describe()

Survived
count  891.000000
mean     0.383838
std      0.486592
min      0.000000
25%      0.000000
50%      0.000000
75%      1.000000
max      1.000000

In [94]:
# splitting the data into Train and Test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(Indepen, Depen,
                                        test_size = 0.25, random_state = 10)
print(type(X_train))
print(type(Y_train))
print(type(X_test))
print(type(Y_test))
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
(668, 6)
(668, 1)
(223, 6)
(223, 1)


In [95]:
#apply  labelcounter Pclass
print(np.unique(X_train.Pclass,return_counts=True))
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
X_train.Pclass=LE.fit_transform(X_train.Pclass)
print(np.unique(X_train.Pclass,return_counts=True))

(array([1, 2, 3], dtype=int64), array([161, 142, 365], dtype=int64))
(array([0, 1, 2], dtype=int64), array([161, 142, 365], dtype=int64))


In [96]:
#apply  labelcounter Sex
print(np.unique(X_train.Sex,return_counts=True))
from sklearn.preprocessing import LabelEncoder
LE1=LabelEncoder()
X_train.Sex=LE1.fit_transform(X_train.Sex)
print(np.unique(X_train.Sex,return_counts=True))

(array(['female', 'male'], dtype=object), array([247, 421], dtype=int64))
(array([0, 1]), array([247, 421], dtype=int64))


In [97]:
#apply  labelcounter SibSp
print(np.unique(X_train.SibSp,return_counts=True))
from sklearn.preprocessing import LabelEncoder
LE2=LabelEncoder()
X_train.SibSp=LE2.fit_transform(X_train.SibSp)
print(np.unique(X_train.SibSp,return_counts=True))

(array([0, 1, 2, 3, 4, 5, 8], dtype=int64), array([457, 155,  21,  12,  11,   5,   7], dtype=int64))
(array([0, 1, 2, 3, 4, 5, 6], dtype=int64), array([457, 155,  21,  12,  11,   5,   7], dtype=int64))


In [98]:
#apply  labelcounter Parch
print(np.unique(X_train.Parch,return_counts=True))
from sklearn.preprocessing import LabelEncoder
LE3=LabelEncoder()
X_train.Parch=LE3.fit_transform(X_train.Parch)
print(np.unique(X_train.Parch,return_counts=True))

(array([0, 1, 2, 3, 4, 5, 6], dtype=int64), array([497,  96,  61,   5,   3,   5,   1], dtype=int64))
(array([0, 1, 2, 3, 4, 5, 6], dtype=int64), array([497,  96,  61,   5,   3,   5,   1], dtype=int64))


In [99]:
X_train.columns

Index(['Age', 'Fare', 'Pclass', 'Sex', 'SibSp', 'Parch'], dtype='object')

In [100]:
# incl cont - Age,Fare
#Cat - Pclass,Sex,Sibsp,Parch
#apply one hot enconding on categorical
from sklearn.preprocessing import OneHotEncoder
categories=np.array([2,3,4,5])
OHE = OneHotEncoder(n_values='auto',categorical_features = categories, sparse = False, handle_unknown = 'ignore')
X_train = OHE.fit_transform(X_train)
X_train.shape

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [83]:
# DecisionTree Classifier
# build grid search parameters
parms = {'min_samples_split': [10,8,5,3], 
         'min_samples_leaf': [2,3,5,7],
         'min_impurity_decrease': [0.001,0.005,0.02,0.01]} 
# perform grid search
from sklearn.tree import DecisionTreeClassifier
CART = DecisionTreeClassifier(class_weight='balanced')
from sklearn.model_selection import GridSearchCV
CV = GridSearchCV(estimator = CART,param_grid = parms, scoring = 'roc_auc',cv=3,refit=True,
                           return_train_score = True,verbose=10,n_jobs=1)
CV.fit(X_train,Y_train)

Fitting 3 folds for each of 64 candidates, totalling 192 fits
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=10 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=10, score=0.8351081670300184, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=10 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=10, score=0.7361646822069428, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=10 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=10, score=0.8517215061058345, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=8 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=8, score=0.8151517692436693, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=8 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=8, score=0.730672480

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    0.1s remaining:    0.0s


[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=5 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=5, score=0.8266621438263229, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=3 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=3, score=0.7838755659902734, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=3 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=3, score=0.7223712896193191, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=3 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=3, score=0.8186058344640434, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=10 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=10, score=0.8387137346973, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_

[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    0.1s remaining:    0.0s


[CV]  min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=8, score=0.8593537991858888, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=5 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=5, score=0.8052574207613618, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=5 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=5, score=0.7206523561965454, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=5 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=5, score=0.8375593622795116, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=3, score=0.8079406339091062, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.001, min_sample

[CV]  min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=5, score=0.8515094979647219, total=   0.0s
[CV] min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=3, score=0.8556934428978702, total=   0.0s
[CV] min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=3, score=0.7516770082173403, total=   0.0s
[CV] min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=3, score=0.8515094979647219, total=   0.0s
[CV] min_impurity_decrease=0.005, min_samples_leaf=5, min_samples_split=10 
[CV]  min_impurity_decrease=0.005, min_samples_leaf=5, min_samples_split=10, score=0.8706188160321985, total=   0.0s
[CV] min_impurity_decrease=0.005, min_samples_leaf=5, min_samples_split=10 
[CV]  min_impurity_decrease=0.005, min_sam

[CV]  min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=8, score=0.746268656716418, total=   0.0s
[CV] min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=8 
[CV]  min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=8, score=0.8209803256445047, total=   0.0s
[CV] min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=5 
[CV]  min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=5, score=0.7625356364246185, total=   0.0s
[CV] min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=5 
[CV]  min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=5, score=0.746268656716418, total=   0.0s
[CV] min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=5 
[CV]  min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=5, score=0.8209803256445047, total=   0.0s
[CV] min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.02, min_samples_leaf=3, min

[CV]  min_impurity_decrease=0.01, min_samples_leaf=3, min_samples_split=5, score=0.7568338084856616, total=   0.0s
[CV] min_impurity_decrease=0.01, min_samples_leaf=3, min_samples_split=5 
[CV]  min_impurity_decrease=0.01, min_samples_leaf=3, min_samples_split=5, score=0.8705902306648575, total=   0.0s
[CV] min_impurity_decrease=0.01, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.01, min_samples_leaf=3, min_samples_split=3, score=0.8693610598691934, total=   0.0s
[CV] min_impurity_decrease=0.01, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.01, min_samples_leaf=3, min_samples_split=3, score=0.7568338084856616, total=   0.0s
[CV] min_impurity_decrease=0.01, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.01, min_samples_leaf=3, min_samples_split=3, score=0.8705902306648575, total=   0.0s
[CV] min_impurity_decrease=0.01, min_samples_leaf=5, min_samples_split=10 
[CV]  min_impurity_decrease=0.01, min_samples_leaf=5, 

[Parallel(n_jobs=1)]: Done 192 out of 192 | elapsed:    3.5s finished


GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight='balanced', criterion='gini',
            max_depth=None, max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=1,
       param_grid={'min_samples_split': [10, 8, 5, 3], 'min_samples_leaf': [2, 3, 5, 7], 'min_impurity_decrease': [0.001, 0.005, 0.02, 0.01]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='roc_auc', verbose=10)

In [84]:
X_test.Pclass=LE.transform(X_test.Pclass)
print(np.unique(X_test.Pclass,return_counts=True))

ValueError: y contains previously unseen labels: [0]

In [81]:
X_test.Sex=LE1.transform(X_test.Sex)
print(np.unique(X_test.Sex,return_counts=True))

ValueError: y contains previously unseen labels: [0, 1]

In [58]:
X_test.SibSp=LE2.transform(X_test.SibSp)
print(np.unique(X_test.SibSp,return_counts=True))

(array([0, 1, 2, 3, 4], dtype=int64), array([151,  54,   7,   4,   7], dtype=int64))


In [61]:
X_test.Parch=LE3.transform(X_test.Parch)
print(np.unique(X_test.Parch,return_counts=True))

(array([0, 1, 2, 4], dtype=int64), array([181,  22,  19,   1], dtype=int64))


In [62]:
X_test = OHE.transform(X_test)

ValueError: could not convert string to float: 'male'

In [42]:
# split the file into Independent and dependent variables
Setcolumns=list(['Age','Fare','Pclass','Sex','SibSp','Parch'])
Indepen=pd.DataFrame(Tit1,columns=Setcolumns)
Indepen.describe()

Age        Fare      Pclass         Sex       SibSp       Parch
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean    29.699118   32.204208    1.308642    0.647587    0.507295    0.381594
std     13.002015   49.693429    0.836071    0.477990    1.005995    0.806057
min      0.420000    0.000000    0.000000    0.000000    0.000000    0.000000
25%     22.000000    7.910400    1.000000    0.000000    0.000000    0.000000
50%     29.699118   14.454200    2.000000    1.000000    0.000000    0.000000
75%     35.000000   31.000000    2.000000    1.000000    1.000000    0.000000
max     80.000000  512.329200    2.000000    1.000000    6.000000    6.000000

In [43]:
Depen=pd.DataFrame(Tit1,columns=['Survived'])
Depen.describe()

Survived
count  891.000000
mean     0.383838
std      0.486592
min      0.000000
25%      0.000000
50%      0.000000
75%      1.000000
max      1.000000

In [44]:
# splitting the data into Train and Test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(Indepen, Depen, test_size = 0.25, random_state = 10)
print(type(X_train))
print(type(Y_train))
print(type(X_test))
print(type(Y_test))
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
(668, 6)
(668, 1)
(223, 6)
(223, 1)


In [45]:
X_test.columns

Index(['Age', 'Fare', 'Pclass', 'Sex', 'SibSp', 'Parch'], dtype='object')

In [46]:
X_train.shape

(668, 6)

In [47]:
X_train.columns

Index(['Age', 'Fare', 'Pclass', 'Sex', 'SibSp', 'Parch'], dtype='object')

In [48]:
# incl cont - Age,Fare
#Cat - Pclass,Sex,Sibsp,Parch
#apply one hot enconding on categorical
from sklearn.preprocessing import OneHotEncoder
categories=np.array([2,3,4,5])
OHE = OneHotEncoder(n_values='auto',categorical_features = categories, sparse = False, handle_unknown = 'ignore')
X_train = OHE.fit_transform(X_train)
X_train.shape

(668, 21)

In [49]:
# DecisionTree Classifier
# build grid search parameters
parms = {'min_samples_split': [10,8,5,3], 
         'min_samples_leaf': [2,3,5,7],
         'min_impurity_decrease': [0.001,0.005,0.02,0.01]} 
# perform grid search
from sklearn.tree import DecisionTreeClassifier
CART = DecisionTreeClassifier(class_weight='balanced')
from sklearn.model_selection import GridSearchCV
CV = GridSearchCV(estimator = CART,param_grid = parms, scoring = 'roc_auc',cv=3,refit=True,
                           return_train_score = True,verbose=10,n_jobs=1)
CV.fit(X_train,Y_train)

Fitting 3 folds for each of 64 candidates, totalling 192 fits
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=10 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=10, score=0.8370367264799597, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=10 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=10, score=0.7361646822069428, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=10 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=10, score=0.8489229986431479, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=8 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=8, score=0.8155290960925708, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=8 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=8, score=0.730672480

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    0.1s remaining:    0.0s



[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=5 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=5, score=0.8130088195386702, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=3 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=3, score=0.781779305718598, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=3 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=3, score=0.7223712896193191, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=3 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=2, min_samples_split=3, score=0.8097862957937585, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=10 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=10, score=0.8387137346973, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_

[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    0.1s remaining:    0.0s



[CV]  min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=8, score=0.7294985745430154, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=8 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=8, score=0.8593537991858888, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=5 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=5, score=0.8034965621331543, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=5 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=5, score=0.7206523561965454, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=5 
[CV]  min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=5, score=0.8402730664857531, total=   0.0s
[CV] min_impurity_decrease=0.001, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.001, min_sampl

[CV]  min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=5, score=0.8556934428978702, total=   0.0s
[CV] min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=5 
[CV]  min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=5, score=0.7516770082173403, total=   0.0s
[CV] min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=5 
[CV]  min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=5, score=0.8515094979647219, total=   0.0s
[CV] min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=3, score=0.8556934428978702, total=   0.0s
[CV] min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=3, score=0.7516770082173403, total=   0.0s
[CV] min_impurity_decrease=0.005, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.005, min_sample

[CV] min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=8 
[CV]  min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=8, score=0.7625356364246185, total=   0.0s
[CV] min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=8 
[CV]  min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=8, score=0.746268656716418, total=   0.0s
[CV] min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=8 
[CV]  min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=8, score=0.8209803256445047, total=   0.0s
[CV] min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=5 
[CV]  min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=5, score=0.7625356364246185, total=   0.0s
[CV] min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=5 
[CV]  min_impurity_decrease=0.02, min_samples_leaf=3, min_samples_split=5, score=0.746268656716418, total=   0.0s
[CV] min_impurity_decrease=0.02, min_samples_leaf=3, min_

[CV]  min_impurity_decrease=0.01, min_samples_leaf=3, min_samples_split=3, score=0.8693610598691934, total=   0.0s
[CV] min_impurity_decrease=0.01, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.01, min_samples_leaf=3, min_samples_split=3, score=0.7568338084856616, total=   0.0s
[CV] min_impurity_decrease=0.01, min_samples_leaf=3, min_samples_split=3 
[CV]  min_impurity_decrease=0.01, min_samples_leaf=3, min_samples_split=3, score=0.8705902306648575, total=   0.0s
[CV] min_impurity_decrease=0.01, min_samples_leaf=5, min_samples_split=10 
[CV]  min_impurity_decrease=0.01, min_samples_leaf=5, min_samples_split=10, score=0.8693610598691934, total=   0.0s
[CV] min_impurity_decrease=0.01, min_samples_leaf=5, min_samples_split=10 
[CV]  min_impurity_decrease=0.01, min_samples_leaf=5, min_samples_split=10, score=0.7568338084856616, total=   0.0s
[CV] min_impurity_decrease=0.01, min_samples_leaf=5, min_samples_split=10 
[CV]  min_impurity_decrease=0.01, min_samples_leaf

[Parallel(n_jobs=1)]: Done 192 out of 192 | elapsed:    3.5s finished


GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight='balanced', criterion='gini',
            max_depth=None, max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=1,
       param_grid={'min_samples_split': [10, 8, 5, 3], 'min_samples_leaf': [2, 3, 5, 7], 'min_impurity_decrease': [0.001, 0.005, 0.02, 0.01]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='roc_auc', verbose=10)

In [50]:
%%time
CVResults = pd.DataFrame(CV.cv_results_)
#print(CVResults)
CVResults.to_excel('CVResutls_CART_Prac.xlsx')

Wall time: 431 ms


In [51]:
print(CV.best_estimator_)

DecisionTreeClassifier(class_weight='balanced', criterion='gini',
            max_depth=None, max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.005, min_impurity_split=None,
            min_samples_leaf=7, min_samples_split=10,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')


In [53]:
print(CV.best_estimator_.feature_importances_)

[0.06037991 0.         0.1334124  0.         0.66096028 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.0617931  0.08345431]


In [54]:
print(CV.best_estimator_.max_features_)

21


In [55]:
print(CV.best_score_)
print(CV.best_params_)

0.8348022436900169
{'min_impurity_decrease': 0.005, 'min_samples_leaf': 7, 'min_samples_split': 10}


In [56]:
print(CV.best_estimator_.n_classes_)
print(CV.best_estimator_.n_features_)
print(CV.best_estimator_.n_outputs_)

2
21
1


In [52]:
from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus
dot_data = StringIO()
export_graphviz(CV.best_estimator_, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

InvocationException: GraphViz's executables not found

In [66]:
X_test=OHE.fit_transform(X_test)
print(X_test.shape)

(223, 32)


In [67]:
#extract only continuous columns
contcolumns=list(['Age','Fare'])
X_test_cont=pd.DataFrame(X_test,columns=contcolumns)
print(X_test_cont.describe())

ValueError: Shape of passed values is (32, 223), indices imply (2, 223)

In [ ]:
#extract only categorical vars
catcolumns=list(['Pclass','Sex','SibSp','Parch'])
X_test_cat=pd.DataFrame(X_test,columns=catcolumns)
print(X_test_cat.describe())

In [65]:
X_test.Pclass = LE.transform(X_test.Pclass)
print(X_test.Pclass.describe())

AttributeError: 'numpy.ndarray' object has no attribute 'Pclass'

In [58]:
# lable encoding for strings on test
X_test.Sex = LE.transform(X_test.Sex)
print(X_test.Sex.describe())

count    223.000000
mean       0.699552
std        0.459484
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: Sex, dtype: float64


In [59]:
# lable encoding for strings on test
X_test.SibSp = LE.transform(X_test.SibSp)
print(X_test.SibSp.describe())

ValueError: y contains previously unseen labels: [3, 4]

In [60]:
# lable encoding for strings on test
X_test.Parch = LE.transform(X_test.Parch)
print(X_test.Parch.describe())

ValueError: y contains previously unseen labels: [4]

In [ ]:
# apply one hot encoding on state and area
X_test = OHE.transform(X_test)
X_test.shape

In [ ]:
# Preidct on Test data and check the confusion matrix
predictTest = CV.predict(X_test)
print(predictTest[0:10])