In [1]:
# K nearest neighbours
import numpy as np
import pandas as pd 

In [2]:
# read IRIS file
import seaborn as sns
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
# split the train data into independent variables (X) and dependent variable (Y)
x_iris = iris.drop('species', axis = 1)
print(x_iris.shape)
y_iris = iris['species']
print(y_iris.shape)
print(type(x_iris))
print(type(y_iris))

(150, 4)
(150,)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [4]:
# Splitting into training and test sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_iris, y_iris, test_size = 0.30, random_state = 0)
print(type(x_train))

<class 'pandas.core.frame.DataFrame'>


In [6]:
# apply k nearest neighbour with K = 1
from sklearn.neighbors import KNeighborsClassifier
init = KNeighborsClassifier(n_neighbors = 1, algorithm = 'auto')
KNN = init.fit(x_train,y_train)

In [7]:
# predict the species on test data
y_KNN1 = KNN.predict(x_test)

In [8]:
# generate confusion matrix
from sklearn.metrics import confusion_matrix, classification_report
print (confusion_matrix(y_test,y_KNN1))
print (classification_report(y_test,y_KNN1))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       1.00      0.94      0.97        18
  virginica       0.92      1.00      0.96        11

avg / total       0.98      0.98      0.98        45



In [9]:
# try with k = 2
init = KNeighborsClassifier(n_neighbors = 2, algorithm = 'auto')
KNN = init.fit(x_train,y_train)
y_KNN1 = KNN.predict(x_test)
print (confusion_matrix(y_test,y_KNN1))
print (classification_report(y_test,y_KNN1))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       1.00      0.94      0.97        18
  virginica       0.92      1.00      0.96        11

avg / total       0.98      0.98      0.98        45



In [10]:
# try with k = 3
init = KNeighborsClassifier(n_neighbors = 3, algorithm = 'auto')
KNN = init.fit(x_train,y_train)
y_KNN1 = KNN.predict(x_test)
print (confusion_matrix(y_test,y_KNN1))
print (classification_report(y_test,y_KNN1))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       1.00      0.94      0.97        18
  virginica       0.92      1.00      0.96        11

avg / total       0.98      0.98      0.98        45



In [11]:
# try with k = 4
init = KNeighborsClassifier(n_neighbors = 20, algorithm = 'auto')
KNN = init.fit(x_train,y_train)
y_KNN1 = KNN.predict(x_test)
print (confusion_matrix(y_test,y_KNN1))
print (classification_report(y_test,y_KNN1))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       1.00      0.94      0.97        18
  virginica       0.92      1.00      0.96        11

avg / total       0.98      0.98      0.98        45

