In [9]:
import numpy as np

In [3]:
i=np.identity(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.arange(1,120,25)

array([  1,  26,  51,  76, 101])

In [15]:
list1=[10,58,68,32,98]
arrid=np.array(list1)
arrid

array([10, 58, 68, 32, 98])

In [16]:
print(type(arrid))

<class 'numpy.ndarray'>


In [17]:
list1+2

TypeError: can only concatenate list (not "int") to list

In [18]:
arrid+2

array([ 12,  60,  70,  34, 100])

In [21]:
list2=[[10,25,35],[45,20,65],[82,58,69]]
arrid2=np.array(list2)
arrid2

array([[10, 25, 35],
       [45, 20, 65],
       [82, 58, 69]])

In [22]:
arr_f=np.array(list2,dtype='float')
arr_f

array([[10., 25., 35.],
       [45., 20., 65.],
       [82., 58., 69.]])

In [23]:
arr_ft=np.array(list2,dtype='float')
arr_ft

array([[10., 25., 35.],
       [45., 20., 65.],
       [82., 58., 69.]])

In [24]:
arr_ft.astype('int')

array([[10, 25, 35],
       [45, 20, 65],
       [82, 58, 69]])

In [25]:
arr_bl=np.array([1,25,0],dtype='bool')
arr_bl

array([ True,  True, False])

In [26]:
arr_obj=np.array([0,1,'a','s'],dtype='object')
arr_obj

array([0, 1, 'a', 's'], dtype=object)

In [27]:
type(arr_obj)

numpy.ndarray

In [28]:
arr_obj_t=np.array([0,1,'a','s'],dtype='object')
arr_obj_t

array([0, 1, 'a', 's'], dtype=object)

In [35]:
ls=arr_obj_t.tolist()
print(ls)
print(type(ls))

[0, 1, 'a', 's']
<class 'list'>


In [36]:
list2=([10.52,11.12,12.32,23.45],[25.68,18.75,69.42,45.36],[58.14,78.24,85.78,43.98])
arr_list2=np.array(list2,dtype='float')
arr_list2

array([[10.52, 11.12, 12.32, 23.45],
       [25.68, 18.75, 69.42, 45.36],
       [58.14, 78.24, 85.78, 43.98]])

In [38]:
print('Shape:',arr_list2.shape)
print('Size:',arr_list2.size)
print('dtype:',arr_list2.dtype)
print('number of dimensions:',arr_list2.ndim)

Shape: (3, 4)
Size: 12
dtype: float64
number of dimensions: 2


In [40]:
#How to extract specific items from an array
arr_list2[:2,:2]

array([[10.52, 11.12],
       [25.68, 18.75]])

In [42]:
arr_list2[2:3]

array([[58.14, 78.24, 85.78, 43.98]])

In [41]:
list2[:2,:2]

TypeError: tuple indices must be integers or slices, not tuple