In [1]:
#importing and reading the data
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

# Because my Jupyter was showing only last line output, so need to add
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

chrn=pd.read_csv('Churn.csv')
chrn.describe()
chrn.shape

(3333, 21)

In [2]:
#checking if null exists are not
chrn.isnull().sum()

AccountLength    0
VMailMessage     0
DayMins          0
EveMins          0
NightMins        0
IntlMins         0
CustServCalls    0
Churn            0
IntlPlan         0
VMailPlan        0
DayCalls         0
DayCharge        0
EveCalls         0
EveCharge        0
NightCalls       0
NightCharge      0
IntlCalls        0
IntlCharge       0
State            0
AreaCode         0
Phone            0
dtype: int64

In [10]:
chrn.corr(method='pearson')

AccountLength  VMailMessage   DayMins   EveMins  NightMins  \
AccountLength       1.000000     -0.004628  0.006216 -0.006757  -0.008955   
VMailMessage       -0.004628      1.000000  0.000778  0.017562   0.007681   
DayMins             0.006216      0.000778  1.000000  0.007043   0.004323   
EveMins            -0.006757      0.017562  0.007043  1.000000  -0.012584   
NightMins          -0.008955      0.007681  0.004323 -0.012584   1.000000   
IntlMins            0.009514      0.002856 -0.010155 -0.011035  -0.015207   
CustServCalls      -0.003796     -0.013263 -0.013423 -0.012985  -0.009288   
Churn               0.016541     -0.089728  0.205151  0.092796   0.035493   
IntlPlan            0.024735      0.008745  0.049396  0.019100  -0.028905   
VMailPlan           0.002918      0.956927 -0.001684  0.021545   0.006079   
DayCalls            0.038470     -0.009548  0.006750 -0.021451   0.022938   
DayCharge           0.006214      0.000776  1.000000  0.007050   0.004324   
EveCalls            0.019260     -0.005864  0.015769 -0.011430  -0.002093   
EveCharge          -0.006745      0.017578  0.007029  1.000000  -0.012592   
NightCalls         -0.013176      0.007123  0.022972  0.007586   0.011204   
NightCharge        -0.008960      0.007663  0.004300 -0.012593   0.999999   
IntlCalls           0.020661      0.013957  0.008033  0.002541  -0.012353   
IntlCharge          0.009546      0.002884 -0.010092 -0.011067  -0.015180   
AreaCode           -0.012463     -0.001994 -0.008264  0.003580  -0.005825   

               IntlMins  CustServCalls     Churn  IntlPlan  VMailPlan  \
AccountLength  0.009514      -0.003796  0.016541  0.024735   0.002918   
VMailMessage   0.002856      -0.013263 -0.089728  0.008745   0.956927   
DayMins       -0.010155      -0.013423  0.205151  0.049396  -0.001684   
EveMins       -0.011035      -0.012985  0.092796  0.019100   0.021545   
NightMins     -0.015207      -0.009288  0.035493 -0.028905   0.006079   
IntlMins       1.000000      -0.009640  0.068239  0.045871  -0.001318   
CustServCalls -0.009640       1.000000  0.208750 -0.024522  -0.017824   
Churn          0.068239       0.208750  1.000000  0.259852  -0.102148   
IntlPlan       0.045871      -0.024522  0.259852  1.000000   0.006006   
VMailPlan     -0.001318      -0.017824 -0.102148  0.006006   1.000000   
DayCalls       0.021565      -0.018942  0.018459  0.003755  -0.011086   
DayCharge     -0.010157      -0.013427  0.205151  0.049398  -0.001686   
EveCalls       0.008703       0.002423  0.009233  0.006114  -0.006444   
EveCharge     -0.011043      -0.012987  0.092786  0.019106   0.021559   
NightCalls    -0.013605      -0.012802  0.006141  0.012451   0.015553   
NightCharge   -0.015214      -0.009277  0.035496 -0.028913   0.006064   
IntlCalls      0.032304      -0.017561 -0.052844  0.017366   0.007618   
IntlCharge     0.999993      -0.009675  0.068259  0.045780  -0.001276   
AreaCode      -0.018288       0.027572  0.006174  0.048551  -0.000747   

               DayCalls  DayCharge  EveCalls  EveCharge  NightCalls  \
AccountLength  0.038470   0.006214  0.019260  -0.006745   -0.013176   
VMailMessage  -0.009548   0.000776 -0.005864   0.017578    0.007123   
DayMins        0.006750   1.000000  0.015769   0.007029    0.022972   
EveMins       -0.021451   0.007050 -0.011430   1.000000    0.007586   
NightMins      0.022938   0.004324 -0.002093  -0.012592    0.011204   
IntlMins       0.021565  -0.010157  0.008703  -0.011043   -0.013605   
CustServCalls -0.018942  -0.013427  0.002423  -0.012987   -0.012802   
Churn          0.018459   0.205151  0.009233   0.092786    0.006141   
IntlPlan       0.003755   0.049398  0.006114   0.019106    0.012451   
VMailPlan     -0.011086  -0.001686 -0.006444   0.021559    0.015553   
DayCalls       1.000000   0.006753  0.006462  -0.021449   -0.019557   
DayCharge      0.006753   1.000000  0.015769   0.007036    0.022972   
EveCalls       0.006462   0.015769  1.000000  -0.011423    0.007710   
EveCharge     -0.02

In [3]:
#correlation matrix - continuous variables
corr=chrn.corr()
corr

#Feature Engineering - Find out the most correlated columns with churn and use only those columns in model
corr1=chrn.corr()
corl=corr.sort_values('Churn')
cos=corrl['Churn'][corrl['Churn'].values>0.1].index.values
cos

AccountLength  VMailMessage   DayMins   EveMins  NightMins  \
AccountLength       1.000000     -0.004628  0.006216 -0.006757  -0.008955   
VMailMessage       -0.004628      1.000000  0.000778  0.017562   0.007681   
DayMins             0.006216      0.000778  1.000000  0.007043   0.004323   
EveMins            -0.006757      0.017562  0.007043  1.000000  -0.012584   
NightMins          -0.008955      0.007681  0.004323 -0.012584   1.000000   
IntlMins            0.009514      0.002856 -0.010155 -0.011035  -0.015207   
CustServCalls      -0.003796     -0.013263 -0.013423 -0.012985  -0.009288   
Churn               0.016541     -0.089728  0.205151  0.092796   0.035493   
IntlPlan            0.024735      0.008745  0.049396  0.019100  -0.028905   
VMailPlan           0.002918      0.956927 -0.001684  0.021545   0.006079   
DayCalls            0.038470     -0.009548  0.006750 -0.021451   0.022938   
DayCharge           0.006214      0.000776  1.000000  0.007050   0.004324   
EveCalls            0.019260     -0.005864  0.015769 -0.011430  -0.002093   
EveCharge          -0.006745      0.017578  0.007029  1.000000  -0.012592   
NightCalls         -0.013176      0.007123  0.022972  0.007586   0.011204   
NightCharge        -0.008960      0.007663  0.004300 -0.012593   0.999999   
IntlCalls           0.020661      0.013957  0.008033  0.002541  -0.012353   
IntlCharge          0.009546      0.002884 -0.010092 -0.011067  -0.015180   
AreaCode           -0.012463     -0.001994 -0.008264  0.003580  -0.005825   

               IntlMins  CustServCalls     Churn  IntlPlan  VMailPlan  \
AccountLength  0.009514      -0.003796  0.016541  0.024735   0.002918   
VMailMessage   0.002856      -0.013263 -0.089728  0.008745   0.956927   
DayMins       -0.010155      -0.013423  0.205151  0.049396  -0.001684   
EveMins       -0.011035      -0.012985  0.092796  0.019100   0.021545   
NightMins     -0.015207      -0.009288  0.035493 -0.028905   0.006079   
IntlMins       1.000000      -0.009640  0.068239  0.045871  -0.001318   
CustServCalls -0.009640       1.000000  0.208750 -0.024522  -0.017824   
Churn          0.068239       0.208750  1.000000  0.259852  -0.102148   
IntlPlan       0.045871      -0.024522  0.259852  1.000000   0.006006   
VMailPlan     -0.001318      -0.017824 -0.102148  0.006006   1.000000   
DayCalls       0.021565      -0.018942  0.018459  0.003755  -0.011086   
DayCharge     -0.010157      -0.013427  0.205151  0.049398  -0.001686   
EveCalls       0.008703       0.002423  0.009233  0.006114  -0.006444   
EveCharge     -0.011043      -0.012987  0.092786  0.019106   0.021559   
NightCalls    -0.013605      -0.012802  0.006141  0.012451   0.015553   
NightCharge   -0.015214      -0.009277  0.035496 -0.028913   0.006064   
IntlCalls      0.032304      -0.017561 -0.052844  0.017366   0.007618   
IntlCharge     0.999993      -0.009675  0.068259  0.045780  -0.001276   
AreaCode      -0.018288       0.027572  0.006174  0.048551  -0.000747   

               DayCalls  DayCharge  EveCalls  EveCharge  NightCalls  \
AccountLength  0.038470   0.006214  0.019260  -0.006745   -0.013176   
VMailMessage  -0.009548   0.000776 -0.005864   0.017578    0.007123   
DayMins        0.006750   1.000000  0.015769   0.007029    0.022972   
EveMins       -0.021451   0.007050 -0.011430   1.000000    0.007586   
NightMins      0.022938   0.004324 -0.002093  -0.012592    0.011204   
IntlMins       0.021565  -0.010157  0.008703  -0.011043   -0.013605   
CustServCalls -0.018942  -0.013427  0.002423  -0.012987   -0.012802   
Churn          0.018459   0.205151  0.009233   0.092786    0.006141   
IntlPlan       0.003755   0.049398  0.006114   0.019106    0.012451   
VMailPlan     -0.011086  -0.001686 -0.006444   0.021559    0.015553   
DayCalls       1.000000   0.006753  0.006462  -0.021449   -0.019557   
DayCharge      0.006753   1.000000  0.015769   0.007036    0.022972   
EveCalls       0.006462   0.015769  1.000000  -0.011423    0.007710   
EveCharge     -0.02

NameError: name 'corrl' is not defined

In [21]:
chrn['AreaCode'].value_counts()

415    1655
510     840
408     838
Name: AreaCode, dtype: int64

In [27]:
#anova test for continuous vs categorical
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

hp_lm=ols('Churn~State', data=chrn).fit()
aov_table = sm.stats.anova_lm(hp_lm)
aov_table

df      sum_sq   mean_sq         F    PR(>F)
State        1.0    0.025001  0.025001  0.201649  0.653423
Residual  3331.0  412.981300  0.123981       NaN       NaN

In [29]:
hp_lm=ols('Churn~AreaCode', data=chrn).fit()
aov_table = sm.stats.anova_lm(hp_lm)
aov_table

df      sum_sq   mean_sq         F    PR(>F)
AreaCode     1.0    0.004377  0.004377  0.035304  0.850971
Residual  3331.0  413.001923  0.123987       NaN       NaN

In [38]:
hp_lm=ols('Churn~IntlPlan', data=chrn).fit()
aov_table = sm.stats.anova_lm(hp_lm)
aov_table

df      sum_sq    mean_sq           F        PR(>F)
IntlPlan     1.0   27.887417  27.887417  241.206004  1.433606e-52
Residual  3331.0  385.118883   0.115617         NaN           NaN

In [4]:
#apply  labelcounter Areacode
print(np.unique(chrn.IntlPlan,return_counts=True))
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
chrn.IntlPlan=LE.fit_transform(chrn.IntlPlan)
print(np.unique(chrn.IntlPlan,return_counts=True))

(array([0, 1], dtype=int64), array([3010,  323], dtype=int64))
(array([0, 1], dtype=int64), array([3010,  323], dtype=int64))


In [23]:
#apply  labelcounter State
print(np.unique(chrn.State,return_counts=True))
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
chrn.State=LE.fit_transform(chrn.State)
print(np.unique(chrn.State,return_counts=True))

(array(['AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA',
       'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME',
       'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
       'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype=object), array([ 52,  80,  55,  64,  34,  66,  74,  54,  61,  63,  54,  53,  44,
        73,  58,  71,  70,  59,  51,  65,  70,  62,  73,  84,  63,  65,
        68,  68,  62,  61,  56,  68,  62,  66,  83,  78,  61,  78,  45,
        65,  60,  60,  53,  72,  72,  77,  73,  66,  78, 106,  77],
      dtype=int64))
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]), array([ 52,  80,  55,  64,  34,  66,  74,  54,  61,  63,  54,  53,  44,
        73,  58,  71,  70,  59,  51,  

In [5]:
# split the file into Independent and dependent variables

selcolumns=list(['DayMins', 'CustServCalls','IntlPlan', 'DayCharge'])
indepen=pd.DataFrame(chrn,columns=selcolumns)
indepen.describe()

DayMins  CustServCalls     IntlPlan    DayCharge
count  3333.000000    3333.000000  3333.000000  3333.000000
mean    179.775098       1.562856     0.096910    30.562307
std      54.467389       1.315491     0.295879     9.259435
min       0.000000       0.000000     0.000000     0.000000
25%     143.700000       1.000000     0.000000    24.430000
50%     179.400000       1.000000     0.000000    30.500000
75%     216.400000       2.000000     0.000000    36.790000
max     350.800000       9.000000     1.000000    59.640000

In [6]:
depen=pd.DataFrame(chrn,columns=['Churn'])
depen.describe()

Churn
count  3333.000000
mean      0.144914
std       0.352067
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [13]:
# splitting the data into Train and Test

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(indepen, depen, test_size = 0.30, random_state = 0)
print(type(X_train))
print(type(Y_train))
print(type(X_test))
print(type(Y_test))
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
(2333, 4)
(2333, 1)
(1000, 4)
(1000, 1)


In [14]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
%%time
# build grid search parameters
parms = {'C': [0.5,1,2], 
         'kernel': ["linear","poly","rbf","sigmoid"]}
#build svm object
# perform grid search
from sklearn.svm import SVC
SVM = SVC(class_weight='balanced')
from sklearn.model_selection import GridSearchCV
CV = GridSearchCV(estimator = SVM,param_grid = parms, scoring = 'roc_auc',cv=3,refit=True,
                           return_train_score = True,verbose=10,n_jobs=1)
CV.fit(X_train,Y_train)

Fitting 3 folds for each of 12 candidates, totalling 36 fits
[CV] C=0.5, kernel=linear ............................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ... C=0.5, kernel=linear, score=0.7966948652370648, total=   0.1s
[CV] C=0.5, kernel=linear ............................................
[CV] ... C=0.5, kernel=linear, score=0.8445340678077252, total=   0.1s

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s



[CV] C=0.5, kernel=linear ............................................
[CV] ... C=0.5, kernel=linear, score=0.7819387889137004, total=   0.1s
[CV] C=0.5, kernel=poly ..............................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.6s remaining:    0.0s


[CV] ..... C=0.5, kernel=poly, score=0.8466784707193914, total=   0.1s
[CV] C=0.5, kernel=poly ..............................................


[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.8s remaining:    0.0s


[CV] ..... C=0.5, kernel=poly, score=0.8684831792248671, total=   0.1s
[CV] C=0.5, kernel=poly ..............................................


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    1.1s remaining:    0.0s


[CV] ..... C=0.5, kernel=poly, score=0.8017601471167739, total=   0.1s
[CV] C=0.5, kernel=rbf ...............................................
[CV] ...... C=0.5, kernel=rbf, score=0.8471112859859663, total=   0.1s
[CV] C=0.5, kernel=rbf ...............................................


[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    1.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:    1.6s remaining:    0.0s


[CV] ...... C=0.5, kernel=rbf, score=0.8898485146566988, total=   0.1s
[CV] C=0.5, kernel=rbf ...............................................


[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:    1.9s remaining:    0.0s


[CV] ...... C=0.5, kernel=rbf, score=0.8418363325889924, total=   0.1s
[CV] C=0.5, kernel=sigmoid ...........................................


[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:    2.2s remaining:    0.0s


[CV] .. C=0.5, kernel=sigmoid, score=0.5202177191947013, total=   0.1s
[CV] C=0.5, kernel=sigmoid ...........................................
[CV] .. C=0.5, kernel=sigmoid, score=0.5666142042101121, total=   0.1s
[CV] C=0.5, kernel=sigmoid ...........................................
[CV] .. C=0.5, kernel=sigmoid, score=0.5165637724944174, total=   0.1s
[CV] C=1, kernel=linear ..............................................
[CV] ..... C=1, kernel=linear, score=0.7966686340087874, total=   0.1s
[CV] C=1, kernel=linear ..............................................
[CV] ...... C=1, kernel=linear, score=0.844507836579448, total=   0.1s
[CV] C=1, kernel=linear ..............................................
[CV] ..... C=1, kernel=linear, score=0.7819519243399449, total=   0.1s
[CV] C=1, kernel=poly ................................................
[CV] ....... C=1, kernel=poly, score=0.8475309856384026, total=   0.2s
[CV] C=1, kernel=poly ................................................
[CV] .

[Parallel(n_jobs=1)]: Done  36 out of  36 | elapsed:   10.3s finished


Wall time: 10.7 s


In [16]:
%%time
CVResults = pd.DataFrame(CV.cv_results_)
#print(CVResults)
CVResults.to_excel('CVResutls_SVM_Prac.xlsx')

Wall time: 6.67 s


In [17]:
print(CV.best_estimator_)

SVC(C=2, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)


In [18]:
# Preidct on Test data and check the confusion matrix
predictTest = CV.predict(X_test)
print(predictTest[0:10])

[1 0 0 0 1 1 1 0 0 1]


In [19]:
# generate confusion matrix
# import confusion matrix and classification report
from sklearn.metrics import confusion_matrix, classification_report
print (confusion_matrix(Y_test,predictTest))
print (classification_report(Y_test,predictTest))

[[704 158]
 [ 25 113]]
              precision    recall  f1-score   support

           0       0.97      0.82      0.88       862
           1       0.42      0.82      0.55       138

   micro avg       0.82      0.82      0.82      1000
   macro avg       0.69      0.82      0.72      1000
weighted avg       0.89      0.82      0.84      1000



In [20]:
# generate ROC curve
from sklearn.metrics import roc_auc_score, roc_curve
# AUC for class 1
AUC = roc_auc_score(Y_test, predictTest)
print(AUC)
# AUC for class 0
AUC0 = roc_auc_score(Y_test, predictTest)
print(AUC0)
# define variables for True Positive Rate and Falst Positive Rate & threshold value
TPR = dict()
FPR = dict()
THR = dict()
FPR, TPR, THR = roc_curve(Y_test, predictTest)

0.8177729580685296
0.8177729580685296


In [21]:
import matplotlib.pyplot as plt
plt.figure()
# plot the FPR as X-axis and TPR as Y-axis
plt.plot(FPR, TPR)
# plot the minimum line 
plt.plot([0,1], [0,1], color='navy', linestyle = '--')
# set X and Y limits
plt.xlim([0.0, 1.05])
plt.ylim([0.0, 1.05])
# mention lables for X and Y
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC')
plt.show()

<Figure size 640x480 with 0 Axes>

(0.0, 1.05)

(0.0, 1.05)

Text(0.5, 0, 'False Positive Rate')

Text(0, 0.5, 'True Positive Rate')

Text(0.5, 1.0, 'ROC')

<Figure size 640x480 with 1 Axes>